=== jw200101-removeme/SlimBatch/src/main/java/com/mavenagile/slimbatch/config/slim-batch.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by secure (secure) -->
<!--W3C Schema generated by XMLSpy v2005 rel. 3 U (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:complexType name="BatchType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="placeholderProperties" type="IncludeType" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="include" type="IncludeType" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="listener" type="ListenerType" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="datasource" type="BeanType" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="bean" type="BeanType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="nodeClass" type="xs:string" fixed="com.mavenagile.slimbatch.config.Configuration" />
	</xs:complexType>



	<xs:complexType name="JobType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="properties" type="PropertiesType" minOccurs="0" maxOccurs="1" />
			<xs:element name="listeners" type="ListenersType" minOccurs="0" maxOccurs="1" />
			<xs:element name="step" type="StepType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="nodeClass" type="xs:string" fixed="com.mavenagile.slimbatch.confi.elements.Job" />
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>



	<xs:complexType name="PropertyType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="nodeClass" fixed="com.mavenagile.slimbatch.confi.elements.CProperty" />
				<xs:attribute name="name" type="xs:string" use="required" />
				<xs:attribute name="type" type="xs:string" use="optional" default="string" />
				<xs:attribute name="value" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="PropertiesType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="property" type="PropertyType" />
		</xs:sequence>
		<xs:attribute name="nodeClass" type="xs:string" fixed="com.mavenagile.slimbatch.confi.elements.CProperties" />
	</xs:complexType>

	<xs:complexType name="ListenerType">
		<xs:attribute name="ref" type="xs:string" use="required" />
		<xs:attribute name="nodeClass" type="xs:string" fixed="com.mavenagile.slimbatch.confi.elements.Listener" />
	</xs:complexType>

	<xs:complexType name="ListenersType">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="listener" type="ListenerType" />
		</xs:sequence>
		<xs:attribute name="nodeClass" type="xs:string" fixed="com.mavenagile.slimbatch.confi.elements.Listeners" />
	</xs:complexType>

	<xs:complexType name="IncludeType">
		<xs:attribute name="resource" type="xs:string" />
		<xs:attribute name="nodeClass" type="xs:string" fixed="com.mavenagile.slimbatch.confi.elements.Include" />
	</xs:complexType>


	<xs:complexType name="StepType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="transaction" type="TransactionType" minOccurs="0" maxOccurs="1" />
			<xs:element name="partition" type="PartitionType" minOccurs="0" maxOccurs="1" />
			<xs:choice minOccurs="1" maxOccurs="1">
				<xs:element name="batchlet" type="BatchletType" minOccurs="1" maxOccurs="1" />
				<xs:element name="chunk" type="ChunkType" minOccurs="1" maxOccurs="1" />
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="nodeClass" type="xs:string" fixed="com.mavenagile.slimbatch.confi.elements.Step" />
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="MapperType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="properties" type="PropertiesType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="ref" type="xs:string" use="required" />
		<xs:attribute name="nodeClass" type="xs:string" fixed="com.mavenagile.slimbatch.confi.elements.CBean" />
	</xs:complexType>

	<xs:complexType name="ChunkType">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="reader" type="APIBeanType" />
			<xs:element name="processor" type="APIBeanType" />
			<xs:element name="writer" type="APIBeanType" />
		</xs:sequence>
		<xs:attribute name="nodeClass" type="xs:string" fixed="com.mavenagile.slimbatch.confi.elements.Chunk" />
		<xs:attribute name="items" type="xs:int" use="optional" />
		<xs:attribute name="skips" type="xs:int" use="optional" />
		<xs:attribute name="retrys" type="xs:int" use="optional" />
	</xs:complexType>

	<xs:complexType name="BatchletType">
	</xs:complexType>

	<xs:complexType name="TransactionType">
		<xs:attribute name="commitSize" type="xs:int" use="required" />
		<xs:attribute name="datasource" type="xs:string" use="required" />
		<xs:attribute name="nodeClass" type="xs:string" fixed="com.mavenagile.slimbatch.confi.elements.Transaction" />
	</xs:complexType>

	<xs:complexType name="PartitionType">
		<xs:sequence>
			<xs:element name="mapper" type="MapperType" />
		</xs:sequence>
		<xs:attribute name="nodeClass" type="xs:string" fixed="com.mavenagile.slimbatch.confi.elements.Partition" />
	</xs:complexType>

	<xs:complexType name="APIBeanType">
		<xs:sequence>
			<xs:element name="properties" type="PropertiesType" minOccurs="0" maxOccurs="1" nillable="true" />
		</xs:sequence>
		<xs:attribute name="ref" type="xs:string" use="required" />
		<xs:attribute name="nodeClass" type="xs:string" fixed="com.mavenagile.slimbatch.confi.elements.CBean" />
	</xs:complexType>

	<xs:complexType name="BeanType">
		<xs:sequence>
			<xs:element name="properties" type="PropertiesType" minOccurs="0" maxOccurs="1" nillable="true" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required" />
		<xs:attribute name="class" type="xs:string" use="required" />
		<xs:attribute name="nodeClass" type="xs:string" fixed="com.mavenagile.slimbatch.confi.elements.CBean" />
		<xs:attribute name="singleton" type="xs:boolean"></xs:attribute>
	</xs:complexType>

	<xs:element name="job" type="JobType">
	</xs:element>
	<xs:element name="batch" type="BatchType">
	</xs:element>

	<xs:element name="beans" type="BatchType">
	</xs:element>
</xs:schema>

=== jw200101-removeme/SlimBatch/src/test/resources/META-INF/batch-jobs/SlimBatch-SillyChunkJobUnPartitionedDerby.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<job id="SillyJob-UnPartitionedDerby" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./slim-batch.xsd">
	<properties>
		<property name="NumberOfRows" value="10" type="int" />
		<property name="Partitions" value="1" type="int" />
	</properties>
	<listeners>
		<listener ref="SillyJobListener" />
	</listeners>
	<step id="SillyStep1">
		<transaction commitSize="20" datasource="dataSourceDerby" />
		<chunk items="10000" skips="100" retrys="10">
			<reader ref="SillyItemReader">
				<properties>
					<property name="Start" value="1" type="int" />
					<property name="End" value="10000" type="int" />
				</properties>
			</reader>
			<processor ref="SillyItemProcessor" />
			<writer ref="SillyItemWriter" />
		</chunk>
	</step>
	<step id="SillyStep2">
		<transaction commitSize="20" datasource="dataSourceDerby" />
		<chunk items="10000" skips="100" retrys="10">
			<reader ref="SillyItemReader">
				<properties>
					<property name="Start" value="10001" type="int" />
					<property name="End" value="20000" type="int" />
				</properties>
			</reader>
			<processor ref="SillyItemProcessor" />
			<writer ref="SillyItemWriter" />
		</chunk>
	</step>
	<step id="SillyStep3">
		<transaction commitSize="20" datasource="dataSourceDerby" />
		<chunk items="10000" skips="100" retrys="10">
			<reader ref="SillyItemReader">
				<properties>
					<property name="Start" value="20001" type="int" />
					<property name="End" value="50000" type="int" />
				</properties>
			</reader>
			<processor ref="SillyItemProcessor" />
			<writer ref="SillyItemWriter" />
		</chunk>
	</step>

</job>

=== jw200101-removeme/SlimBatch/src/test/resources/META-INF/slim-batch.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<batch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./slim-batch.xsd">
	<!-- <placeholderProperties resource="/META-INF/batch-dev.properties" /> -->
<!-- 	<placeholderProperties resource="/META-INF/batch-prod.properties" /> -->
	<placeholderProperties resource="/META-INF/batch-test.properties" />
	<include resource="META-INF/beans.xml" />
<!-- 	<include resource="META-INF/batch-jobs/SlimBatch-SillyChunkJobDynamicPartitions.xml" /> -->
<!-- 	<include resource="META-INF/batch-jobs/SlimBatch-SillyChunkJobUnPartitioned.xml" /> -->
	<include resource="META-INF/batch-jobs/SlimBatch-SillyChunkJobDynamicPartitionsDerby.xml" />
	<include resource="META-INF/batch-jobs/SlimBatch-SillyChunkJobUnPartitionedDerby.xml" />
	<include resource="META-INF/batch-jobs/SlimBatch-SillyChunkJobDynamicPartitionsMySQL.xml" />
	<include resource="META-INF/batch-jobs/SlimBatch-SillyChunkJobUnPartitionedMySQL.xml" />

	<listener ref="SillyJobListener" />
	<datasource id="dataSource2" class="${batch.jdbc.driver}">
		<properties>
			<property name="URL" value="${batch.jdbc.url}" />
			<property name="ConnectionAttributes" value="${batch.jdbc.ConnectionAttributes}" />
			<!-- <property name="CreateDatabase" value="${batch.jdbc.CreateDatabase}" type="boolean" /> -->
			<property name="DatabaseName" value="${batch.jdbc.DatabaseName}" />
			<property name="User" value="${batch.jdbc.user}" />
			<property name="Password" value="${batch.jdbc.password}" />
		</properties>
	</datasource>

</batch>

=== jw200101-removeme/SlimBatch/src/test/resources/META-INF/batch-jobs/SlimBatch-SillyChunkJobDynamicPartitionsDerby.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<job id="SillyJob-DynamicPartitionsDerby" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./slim-batch.xsd">
<!-- 	<properties> -->
<!-- 		<property name="JobParmNumberOfRows" value="100000" type="int" /> -->
<!-- 		<property name="JobParmPartitions" value="50" type="int" /> -->
<!-- 	</properties> -->
	<listeners>
		<listener ref="SillyJobListener" />
	</listeners>

	<step id="SillyPartitionedStep">
		<transaction commitSize="20" datasource="dataSourceDerby" />
		<partition>
			<mapper ref="SillyPartitionMapper">
<!-- 				<properties> -->
<!-- 					<property name="NumberOfRows" value="${JobParmNumberOfRows}" type="int" /> -->
<!-- 					<property name="Partitions" value="${JobParmPartitions}" type="int" /> -->
<!-- 				</properties> -->
			</mapper>
		</partition>
		<chunk items="10" skips="100" retrys="10">
			<reader ref="SillyItemReader" />
			<processor ref="SillyItemProcessor" />
			<writer ref="SillyItemWriter" />
		</chunk>
	</step>
</job>
